### ISSUE TITLE
[Function] Search bar automatically retracts after clicking on blank area and jumps to a new tab after clicking on the search result

### ISSUE THREAD

**Issue by IAMIBM** [YunYouJun/valaxy#270]
### Clear and concise description of the problem

1. The search bar can not automatically retract after clicking on a blank area.
2. Can not jump to a new tab after clicking on the search result.

### Suggested solution

N/A

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by YunYouJun** [comment]
I'm sorry, I don't understand what you're referring to. Can you provide a preview video or screenshots.

**Comment by IAMIBM** [comment]
not like this.
![my blog](https://github.com/YunYouJun/valaxy/assets/43950866/4f8a45cc-e10e-4c8b-aa32-118737deecd0)
 a GIF that I want is from another blog.
![good example](https://github.com/YunYouJun/valaxy/assets/43950866/0af9b3d6-14ec-4938-9553-d70b8532f7c7)

**Comment by YunYouJun** [comment]
Got it. I think you mean clickOutside like this.

https://vueuse.org/core/onClickOutside/#onclickoutside

**Comment by IAMIBM** [comment]
> Got it. I think you mean clickOutside like this.
> 
> https://vueuse.org/core/onClickOutside/#onclickoutside

Yes, you got my idea.

**Comment by YunYouJun** [comment]
After some testing and research, I decided not to add the feature.

Since it is a full-screen search rather than a partial search, many topics are implemented without clickOutside for full-screen search (as opposed to modal).
Also, with clickOutside enabled, there were all sorts of mistouch issues and I had a hard time copying the content while keeping the box open.
