### ISSUE TITLE
i18n Interaction

### ISSUE THREAD

**Issue by hifocus** [YunYouJun/valaxy#4]
Following your blog post - https://valaxy.yyj.moe/posts/i18n

Wouldn't it be making more sense to have the SSG framework support the following logics:
- Instead of supporting purely a foreign langauge version, try to think of the blog as a true i18n website; that is, some content is available under different langauges, while some others are not.
- The owner can choose to add in an i18n version of one article, for an example, establish this version under the /en-US folder, and link it to its Chinese (native) version in the front-matter
- The behaviour of the article would then be, remind any visitors that this article is available in other langauges; if the visitor's browser/os langauge match the langauge, an additional banner is displayed reminding the visitor that they could switch the article to their langauge
- The ultimate site generated could have a separate /en-US branch, and all translations on localisation are applied. For an example, “首页” being translated into "Home", per mentioned in this post, and only posts available in the respective langauges are displayed

I believe this would be a better way of designing the i18n philosophy.
There are commercial practices of above ideas, such as the Apple/Microsoft website, and Microsoft Docs

Of course, these are just my immature opinions.

**Comment by hifocus** [comment]
Also, the waline commenting system after the post does not work - by submitting the comment without logging in it returns 'Forbidden', after logging in this issue presists.

**Comment by YunYouJun** [comment]
First, Valaxy allows users to create `en-US` folders to write new articles, routes will be automatically generated.

Of course, there may be more details that need to be optimized, such as adding banner prompts as you said.

CSS i18n is an implementation I tried to solve a blog-specific problem.
Because blogs are different from documents, authors usually don't have the energy to write other versions of every blog post. And blog posts tend to have a unified permalink for easy sharing.

On the other hand, documentation is the opposite. People don't care about links as much as blogs do, because they are usually queried as a whole, rather than independent of each other like blog posts.
As you mentioned business practices, they can and should provide multiple languages ​​for each document.
But blog is different, the author may only write a different language for a certain article, and this is likely to break the unity of the link.

The above is my opinion. I think my purpose is to provide a more convenient way for users. Of course, if they still prefer independent management, such use is also supported.

**Comment by YunYouJun** [comment]
> Also, the waline commenting system after the post does not work - by submitting the comment without logging in it returns 'Forbidden', after logging in this issue presists.

This was caused by a security domain issue, I have fixed it now.

**Comment by YunYouJun** [comment]
https://github.com/YunYouJun/valaxy/issues/9#issuecomment-1114299504
